#!/bin/sh
# Puts a LOADER in .git/hooks/pre-push that runs the version-controlled hook
# beside this file. Wired to `npm run prepare`, so a clone gets it on install.
#
# WHY A LOADER AND NOT `core.hooksPath=.githooks`, which is the usual answer:
# that setting is repo-wide and this repo runs a lot of worktrees — 27 at the
# time of writing. A worktree sitting on a branch cut BEFORE `.githooks/`
# existed has no such directory, and git's behaviour there is to run no hook
# and let the push through, silently. Measured, not assumed. Swapping a working
# safety net for a silent hole on two dozen checkouts is not an improvement.
#
# The loader looks up the hook in whichever worktree is pushing, so a branch
# that changes the hook is tested by its own version — and when the file is
# missing it runs the suite itself rather than waving the push through.
set -e

# the shared .git for a worktree, the real one otherwise
hooks="$(git rev-parse --git-common-dir 2>/dev/null || true)/hooks"
case "$hooks" in
  /hooks) echo "install-hooks: not a git checkout — nothing to install."; exit 0 ;;
esac
mkdir -p "$hooks"

cat > "$hooks/pre-push" <<'LOADER'
#!/bin/sh
# GENERATED by .githooks/install.sh — do not edit; edit .githooks/pre-push.
# Runs the version-controlled hook from the worktree being pushed.
root=$(git rev-parse --show-toplevel 2>/dev/null)
if [ -x "$root/.githooks/pre-push" ]; then
  exec "$root/.githooks/pre-push" "$@"
fi
# This branch predates the versioned hook. Do NOT wave the push through —
# fall back to what the hook has always done.
echo "pre-push: no .githooks/pre-push on this branch — running the full suite."
export PATH="$HOME/.local/bin:$PATH"
npm test -- --passWithNoTests || { echo "pre-push: tests failed. Push aborted."; exit 1; }
LOADER

chmod +x "$hooks/pre-push"
echo "install-hooks: loader installed at $hooks/pre-push"
