import type { BuildSettings } from "../buildup";
import type { BenchCase, CaseLine } from "./score";

/* THE BRIEF CASES (slice 0.3) — real jobs, each with what was said about it
   and the lines a person built from it, line for line from the business's
   book, at the settings it priced them with. Job numbers only: no client
   name, no address.

   3377, 3384 and 3375 were built by hand in another session on 6 and 7
   October 2026, reading everything on the job in ServiceM8, and the build
   was left on each job as a note (JOB 3377 …). 3375 was then approved,
   sent and ACCEPTED by the client: the strongest bar a case can have.
   3377 and 3384 are the builder's own, still to be confirmed by Isaac.

   Every buy price is the book's on the day; a contingency and the duct
   redesign hours are lines of their own, as they were built. */

/** Diamond Air's settings on 6 October 2026: 25% on units, 40% on
    materials, $140 an hour, an 8-hour day; contingency built as lines. */
export const DA_OCT_2026: BuildSettings = { unitMarkupPct: 25, materialMarkupPct: 40, chargeOutCents: 14000, dayHours: 8, contingency: null };

const C77: CaseLine[] = [
  { system: "Downstairs", group: "Units", name: "Ducted indoor, under the floor", code: "PEA-M125HAA", kind: "unit", qty: 1, costCents: 106750, source: "said", why: "“underfloor ducted 10 to 12 kW”" },
  { system: "Downstairs", group: "Units", name: "Outdoor, single phase", code: "PUZ-M125VKA2", kind: "unit", qty: 1, costCents: 222320, source: "said", why: "“single phase”, “western side”" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Nose cone, 2 × 400", code: "NCMIT125-160HAA", kind: "material", qty: 1, costCents: 16254, source: "assumed", why: "made for this unit" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Y 400-300-300", code: "MY161212", kind: "material", qty: 1, costCents: 2906, source: "assumed", why: "run A, four grilles" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Y 300-200-200", code: "MY1288", kind: "material", qty: 3, costCents: 2275, source: "assumed", why: "two on run A, one on run B" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Reducer 400-300", code: "AR4030", kind: "material", qty: 1, costCents: 1715, source: "assumed", why: "run B, two grilles" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Flex 400, 6 m bag", code: "VB400", kind: "material", qty: 2, costCents: 4596, source: "assumed", why: "the nose cone and the return" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Flex 300, 6 m bag", code: "VB300", kind: "material", qty: 1, costCents: 3564, source: "assumed" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Flex 200, 6 m bag", code: "VB200", kind: "material", qty: 6, costCents: 2489, source: "assumed", why: "a bag to each grille" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Uni boot 350 × 150, 8 inch", code: "UB3515", kind: "material", qty: 6, costCents: 2800, source: "said", why: "“six floor grills 350 mm x 150 mm”" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Floor grille 350 × 150, anodised", code: "FGA3515", kind: "material", qty: 6, costCents: 3500, source: "said", why: "“six floor grills 350 mm x 150 mm”; anodised assumed" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Return grille 900 × 550, filtered", kind: "material", qty: 1, costCents: 7966, source: "assumed", why: "sized for 1,000 L/s" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Return box 900 × 550, 2 × 400", kind: "material", qty: 1, costCents: 5446, source: "assumed" },
  { system: "Downstairs", group: "Ductwork and grilles", name: "Duct contingency, 15%", kind: "material", qty: 1, costCents: 15990 },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Spring hangers, 15 to 30 kg", code: "SH30", kind: "material", qty: 4, costCents: 2286, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Wired controller", code: "PAR-41MAAM", kind: "material", qty: 1, costCents: 12530, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Pair coil 3/8 + 5/8", code: "PC3858", kind: "material", qty: 10, unit: "m", costCents: 1481.45, source: "assumed", why: "10 m run" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Interconnect 3C+E", kind: "material", qty: 10, unit: "m", costCents: 180, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "TPS 6 mm²", code: "CBT6TEWH", kind: "material", qty: 25, unit: "m", costCents: 475, source: "assumed", why: "25 m to the board" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "RCBO 32 A", code: "NHPM6RCBD3230CAN", kind: "material", qty: 1, costCents: 3770, source: "assumed", why: "for the outdoor’s 26.5 A" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Isolator 35 A", code: "ALSIPW351", kind: "material", qty: 1, costCents: 2360, source: "assumed", why: "for the outdoor’s 26.5 A" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Rubber feet", code: "CMADJ", kind: "material", qty: 1, costCents: 1372, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Drain", kind: "material", qty: 6, unit: "m", costCents: 305, source: "assumed" },
  { system: "Upstairs", group: "Units", name: "Slim ducted indoor, drain pump built in", code: "PEAD-M71JAAD", kind: "unit", qty: 1, costCents: 72800, source: "said", why: "“upstairs ducted for three rooms”" },
  { system: "Upstairs", group: "Units", name: "Outdoor, single phase", code: "SUZ-M71VAD2", kind: "unit", qty: 1, costCents: 129710, source: "said", why: "“western side”, “single phase”" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Supply adaptor 2 × 300", code: "MSAMI712X30S", kind: "material", qty: 1, costCents: 7932, source: "assumed", why: "made for this unit" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Y 300-250-250", code: "MY121010", kind: "material", qty: 1, costCents: 2275, source: "assumed", why: "bed 2 and bed 3" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Reducer 300-250", code: "MR3025", kind: "material", qty: 1, costCents: 1116, source: "assumed", why: "the main bedroom" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 300, 6 m bag", code: "VB300", kind: "material", qty: 1, costCents: 3564, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 250, 6 m bag", code: "VB250", kind: "material", qty: 3, costCents: 3045, source: "assumed", why: "a bag to each bedroom" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Round ceiling diffuser 250", code: "CD250", kind: "material", qty: 3, costCents: 1887, source: "said", why: "“round grills for the three bedrooms”" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Return grille 600 × 400 eggcrate, filtered", code: "ECF6040", kind: "material", qty: 1, costCents: 4862, source: "assumed", why: "sized for 417 L/s" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Return box 600 × 400", code: "MRA6040-35", kind: "material", qty: 1, costCents: 3739, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 350, 6 m bag", code: "VB350", kind: "material", qty: 1, costCents: 4034, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Duct contingency, 15%", kind: "material", qty: 1, costCents: 6348 },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Wired controller", code: "PAR-41MAAM", kind: "material", qty: 1, costCents: 12530, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Pair coil 3/8 + 5/8", code: "PC3858", kind: "material", qty: 15, unit: "m", costCents: 1481.45, source: "assumed", why: "15 m run" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Interconnect 3C+E", kind: "material", qty: 15, unit: "m", costCents: 180, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "TPS 4 mm²", code: "CBT4TEWH", kind: "material", qty: 25, unit: "m", costCents: 354, source: "assumed", why: "25 m to the board" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "RCBO 25 A", code: "NHPM6RCBD2530CAN", kind: "material", qty: 1, costCents: 3770, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Isolator 35 A", code: "ALSIPW351", kind: "material", qty: 1, costCents: 2360, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Rubber feet", code: "CMADJ", kind: "material", qty: 1, costCents: 1372, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Trunking, 2.4 m lengths", kind: "material", qty: 3, costCents: 2900, source: "assumed", why: "up the western wall" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Drain", kind: "material", qty: 6, unit: "m", costCents: 305, source: "assumed" },
  { system: "Core holes", group: "Core holes", name: "Core hole 200 mm through sandstone, to the rear living", kind: "material", qty: 1, costCents: 0, source: "unknown", why: "“a 200 mm core hole through thick sandstone”" },
  { system: "Core holes", group: "Core holes", name: "Core holes to the rear kitchen", kind: "material", qty: 1, costCents: 0, source: "unknown", why: "“core holes to the rear kitchen”, how many not said" },
  { system: "", group: "Labour", name: "Install, two ducted systems", kind: "labour", qty: 80, unit: "h", costCents: 11200, source: "assumed", why: "40 h a system; the crew isn’t in Luke’s notes" },
  { system: "", group: "Labour", name: "Duct redesign allowance, 3 h a system", kind: "labour", qty: 6, unit: "h", costCents: 11200 },
];

const O1: CaseLine[] = [
  { system: "Downstairs", group: "Units", name: "Daikin Cora 7.1 kW high wall", code: "FTXV71WVMA", kind: "unit", qty: 1, costCents: 45604, source: "said", why: "“Downstairs 7kw High Wall Split”" },
  { system: "Downstairs", group: "Units", name: "Outdoor", code: "RXV71WVMA", kind: "unit", qty: 1, costCents: 106410, source: "said", why: "Daikin, from you" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Pair coil 1/4 + 5/8, 20 m roll", code: "PC1458", kind: "material", qty: 1, costCents: 26251, source: "assumed", why: "pipe size assumed: no Daikin data pack" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Interconnect 3C+E", code: "ELCAC7504", kind: "material", qty: 20, unit: "m", costCents: 180, source: "said", why: "20 m runs, from you" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "TPS 2.5 mm²", code: "CBT2.5TEWH", kind: "material", qty: 20, unit: "m", costCents: 198, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "RCBO 20 A", code: "HAGADC920T", kind: "material", qty: 1, costCents: 3886, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Isolator 20 A", code: "ALSIPW201", kind: "material", qty: 1, costCents: 2279, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Rubber feet", code: "CMADJ", kind: "material", qty: 1, costCents: 1372, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Drain hose", code: "3211201-2", kind: "material", qty: 3, unit: "m", costCents: 305, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Wi-Fi adapter", code: "BRP072C42", kind: "material", qty: 1, costCents: 8872, source: "said", why: "“WIFI DONGLES FOR BOTH”" },
  { system: "Upstairs", group: "Units", name: "Daikin 8.5 kW ducted indoor", code: "FDYAN85AV1", kind: "unit", qty: 1, costCents: 104451, source: "said", why: "“Ducted upstairs”, 8.5 kW from you" },
  { system: "Upstairs", group: "Units", name: "Outdoor, single phase", code: "RZA85C2V1", kind: "unit", qty: 1, costCents: 170250, source: "said" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Supply adaptor 2 × 350", code: "MSADA7102X35FDYA", kind: "material", qty: 1, costCents: 4718, source: "assumed", why: "made for this unit" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Y 14-10-10", code: "MY141010", kind: "material", qty: 1, costCents: 2568, source: "assumed", why: "run A" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "BTO 14-12-10", code: "MB141210", kind: "material", qty: 1, costCents: 2759, source: "assumed", why: "run B" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Y 12-10-10", code: "MY121010", kind: "material", qty: 1, costCents: 2275, source: "assumed", why: "run B" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 350, 6 m bag", code: "VB350", kind: "material", qty: 1, costCents: 4034, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 300, 6 m bag", code: "VB300", kind: "material", qty: 1, costCents: 3564, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 250, 6 m bag", code: "VB250", kind: "material", qty: 5, costCents: 3045, source: "assumed", why: "a bag to each outlet" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Cone diffuser 250", code: "CD250", kind: "material", qty: 5, costCents: 1887, source: "assumed", why: "four bedrooms and the hallway" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Return grille 900 × 400, filtered", kind: "material", qty: 1, costCents: 7466, source: "assumed", why: "not sized from airflow" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Return box 900 × 400, 2 × 400", code: "RAB2900", kind: "material", qty: 1, costCents: 4200, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 400, 6 m bag", code: "VB400", kind: "material", qty: 1, costCents: 4596, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Duct contingency, 15%", kind: "material", qty: 1, costCents: 9126 },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Pair coil 3/8 + 5/8, 20 m roll", code: "PC3858", kind: "material", qty: 1, costCents: 29629, source: "said", why: "20 m runs, from you" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Interconnect 3C+E", kind: "material", qty: 20, unit: "m", costCents: 180, source: "said", why: "20 m runs, from you" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "TPS 4 mm²", code: "CBT4TEWH", kind: "material", qty: 25, unit: "m", costCents: 354, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "RCBO 25 A", code: "NHPM6RCBD2530CAN", kind: "material", qty: 1, costCents: 3770, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Isolator 35 A", code: "ALSIPW351", kind: "material", qty: 1, costCents: 2360, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Rubber feet", code: "CMADJ", kind: "material", qty: 1, costCents: 1372, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Drain", kind: "material", qty: 6, unit: "m", costCents: 305, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Wall controller", code: "BRC1E63", kind: "material", qty: 1, costCents: 10101, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Wi-Fi interface", code: "BRP15B61", kind: "material", qty: 1, costCents: 17061, source: "said", why: "“WIFI DONGLES FOR BOTH”" },
  { system: "Shared", group: "Shared", name: "Shale Grey trunking, 2.4 m lengths", code: "TCAPSG", kind: "material", qty: 8, costCents: 3030, source: "said", why: "one run for both, from you" },
  { system: "", group: "Labour", name: "Install: ducted and a split", kind: "labour", qty: 54, unit: "h", costCents: 11200, source: "assumed", why: "40 h ducted and 14 h split, from your past installs" },
  { system: "", group: "Labour", name: "Duct redesign allowance", kind: "labour", qty: 3, unit: "h", costCents: 11200 },
];

const O2: CaseLine[] = [
  { system: "Downstairs", group: "Units", name: "Daikin Cora 7.1 kW high wall", code: "FTXV71WVMA", kind: "unit", qty: 1, costCents: 45604, source: "said", why: "“Downstairs 7kw High Wall Split”" },
  { system: "Downstairs", group: "Units", name: "Outdoor", code: "RXV71WVMA", kind: "unit", qty: 1, costCents: 106410, source: "said", why: "Daikin, from you" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Pair coil 1/4 + 5/8, 20 m roll", code: "PC1458", kind: "material", qty: 1, costCents: 26251, source: "assumed", why: "pipe size assumed: no Daikin data pack" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Interconnect 3C+E", code: "ELCAC7504", kind: "material", qty: 20, unit: "m", costCents: 180, source: "said", why: "20 m runs, from you" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "TPS 2.5 mm²", code: "CBT2.5TEWH", kind: "material", qty: 20, unit: "m", costCents: 198, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "RCBO 20 A", code: "HAGADC920T", kind: "material", qty: 1, costCents: 3886, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Isolator 20 A", code: "ALSIPW201", kind: "material", qty: 1, costCents: 2279, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Rubber feet", code: "CMADJ", kind: "material", qty: 1, costCents: 1372, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Drain hose", code: "3211201-2", kind: "material", qty: 3, unit: "m", costCents: 305, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Wi-Fi adapter", code: "BRP072C42", kind: "material", qty: 1, costCents: 8872, source: "said", why: "“WIFI DONGLES FOR BOTH”" },
  { system: "Upstairs", group: "Units", name: "Daikin 8.5 kW ducted indoor", code: "FDYAN85AV1", kind: "unit", qty: 1, costCents: 104451, source: "said", why: "“Ducted upstairs”, 8.5 kW from you" },
  { system: "Upstairs", group: "Units", name: "Outdoor, single phase", code: "RZA85C2V1", kind: "unit", qty: 1, costCents: 170250, source: "said" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Supply adaptor 2 × 350", code: "MSADA7102X35FDYA", kind: "material", qty: 1, costCents: 4718, source: "assumed", why: "made for this unit" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Y 14-10-10", code: "MY141010", kind: "material", qty: 1, costCents: 2568, source: "assumed", why: "run A" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "BTO 14-12-10", code: "MB141210", kind: "material", qty: 1, costCents: 2759, source: "assumed", why: "run B" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Y 12-10-10", code: "MY121010", kind: "material", qty: 1, costCents: 2275, source: "assumed", why: "run B" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 350, 6 m bag", code: "VB350", kind: "material", qty: 1, costCents: 4034, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 300, 6 m bag", code: "VB300", kind: "material", qty: 1, costCents: 3564, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 250, 6 m bag", code: "VB250", kind: "material", qty: 5, costCents: 3045, source: "assumed", why: "a bag to each outlet" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Cone diffuser 250", code: "CD250", kind: "material", qty: 5, costCents: 1887, source: "assumed", why: "four bedrooms and the hallway" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Return grille 900 × 400, filtered", kind: "material", qty: 1, costCents: 7466, source: "assumed", why: "not sized from airflow" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Return box 900 × 400, 2 × 400", code: "RAB2900", kind: "material", qty: 1, costCents: 4200, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 400, 6 m bag", code: "VB400", kind: "material", qty: 1, costCents: 4596, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Duct contingency, 15%", kind: "material", qty: 1, costCents: 9126 },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Pair coil 3/8 + 5/8, 20 m roll", code: "PC3858", kind: "material", qty: 1, costCents: 29629, source: "said", why: "20 m runs, from you" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Interconnect 3C+E", kind: "material", qty: 20, unit: "m", costCents: 180, source: "said", why: "20 m runs, from you" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "TPS 4 mm²", code: "CBT4TEWH", kind: "material", qty: 25, unit: "m", costCents: 354, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "RCBO 25 A", code: "NHPM6RCBD2530CAN", kind: "material", qty: 1, costCents: 3770, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Isolator 35 A", code: "ALSIPW351", kind: "material", qty: 1, costCents: 2360, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Rubber feet", code: "CMADJ", kind: "material", qty: 1, costCents: 1372, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Drain", kind: "material", qty: 6, unit: "m", costCents: 305, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Wall controller", code: "BRC1E63", kind: "material", qty: 1, costCents: 10101, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Wi-Fi interface", code: "BRP15B61", kind: "material", qty: 1, costCents: 17061, source: "said", why: "“WIFI DONGLES FOR BOTH”" },
  { system: "Shared", group: "Shared", name: "Shale Grey trunking, 2.4 m lengths", code: "TCAPSG", kind: "material", qty: 8, costCents: 3030, source: "said", why: "one run for both, from you" },
  { system: "", group: "Labour", name: "Install: ducted and a split", kind: "labour", qty: 54, unit: "h", costCents: 11200, source: "assumed", why: "40 h ducted and 14 h split, from your past installs" },
  { system: "", group: "Labour", name: "Duct redesign allowance", kind: "labour", qty: 3, unit: "h", costCents: 11200 },
  { system: "Upstairs", group: "Zoning", name: "Daikin 4-zone controller, 24 V", code: "BRC24Z4B9", kind: "material", qty: 1, costCents: 29345, source: "said", why: "zoning as an option, from you" },
  { system: "Upstairs", group: "Zoning", name: "Zone damper 250, 24 V", code: "MDM250L", kind: "material", qty: 4, costCents: 6296, source: "said" },
  { system: "Upstairs", group: "Zoning", name: "Zone control cable, 12 m", code: "RZCAB12", kind: "material", qty: 4, costCents: 1185, source: "assumed" },
];

const O3: CaseLine[] = [
  { system: "Downstairs", group: "Units", name: "Daikin XL Premium 9.5 kW high wall", code: "FTXM95WVMA", kind: "unit", qty: 1, costCents: 76007.2, source: "said", why: "“compare the Cora with something bigger”" },
  { system: "Downstairs", group: "Units", name: "Outdoor", code: "RXM95WVMA", kind: "unit", qty: 1, costCents: 176859.2, source: "said" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Pair coil 3/8 + 5/8, 20 m roll", code: "PC3858", kind: "material", qty: 1, costCents: 29629, source: "assumed", why: "pipe size assumed: no Daikin data pack" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Interconnect 3C+E", code: "ELCAC7504", kind: "material", qty: 20, unit: "m", costCents: 180, source: "said", why: "20 m runs, from you" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "TPS 4 mm²", code: "CBT4TEWH", kind: "material", qty: 20, unit: "m", costCents: 354, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "RCBO 25 A", code: "NHPM6RCBD2530CAN", kind: "material", qty: 1, costCents: 3770, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Isolator 35 A", code: "ALSIPW351", kind: "material", qty: 1, costCents: 2360, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Rubber feet", code: "CMADJ", kind: "material", qty: 1, costCents: 1372, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Drain hose", code: "3211201-2", kind: "material", qty: 3, unit: "m", costCents: 305, source: "assumed" },
  { system: "Downstairs", group: "Pipe, power and controls", name: "Wi-Fi adapter", code: "BRP072C42", kind: "material", qty: 1, costCents: 8872, source: "said", why: "“WIFI DONGLES FOR BOTH”" },
  { system: "Upstairs", group: "Units", name: "Daikin 8.5 kW ducted indoor", code: "FDYAN85AV1", kind: "unit", qty: 1, costCents: 104451, source: "said", why: "“Ducted upstairs”, 8.5 kW from you" },
  { system: "Upstairs", group: "Units", name: "Outdoor, single phase", code: "RZA85C2V1", kind: "unit", qty: 1, costCents: 170250, source: "said" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Supply adaptor 2 × 350", code: "MSADA7102X35FDYA", kind: "material", qty: 1, costCents: 4718, source: "assumed", why: "made for this unit" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Y 14-10-10", code: "MY141010", kind: "material", qty: 1, costCents: 2568, source: "assumed", why: "run A" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "BTO 14-12-10", code: "MB141210", kind: "material", qty: 1, costCents: 2759, source: "assumed", why: "run B" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Y 12-10-10", code: "MY121010", kind: "material", qty: 1, costCents: 2275, source: "assumed", why: "run B" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 350, 6 m bag", code: "VB350", kind: "material", qty: 1, costCents: 4034, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 300, 6 m bag", code: "VB300", kind: "material", qty: 1, costCents: 3564, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 250, 6 m bag", code: "VB250", kind: "material", qty: 5, costCents: 3045, source: "assumed", why: "a bag to each outlet" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Cone diffuser 250", code: "CD250", kind: "material", qty: 5, costCents: 1887, source: "assumed", why: "four bedrooms and the hallway" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Return grille 900 × 400, filtered", kind: "material", qty: 1, costCents: 7466, source: "assumed", why: "not sized from airflow" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Return box 900 × 400, 2 × 400", code: "RAB2900", kind: "material", qty: 1, costCents: 4200, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Flex 400, 6 m bag", code: "VB400", kind: "material", qty: 1, costCents: 4596, source: "assumed" },
  { system: "Upstairs", group: "Ductwork and grilles", name: "Duct contingency, 15%", kind: "material", qty: 1, costCents: 9126 },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Pair coil 3/8 + 5/8, 20 m roll", code: "PC3858", kind: "material", qty: 1, costCents: 29629, source: "said", why: "20 m runs, from you" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Interconnect 3C+E", kind: "material", qty: 20, unit: "m", costCents: 180, source: "said", why: "20 m runs, from you" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "TPS 4 mm²", code: "CBT4TEWH", kind: "material", qty: 25, unit: "m", costCents: 354, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "RCBO 25 A", code: "NHPM6RCBD2530CAN", kind: "material", qty: 1, costCents: 3770, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Isolator 35 A", code: "ALSIPW351", kind: "material", qty: 1, costCents: 2360, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Rubber feet", code: "CMADJ", kind: "material", qty: 1, costCents: 1372, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Drain", kind: "material", qty: 6, unit: "m", costCents: 305, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Wall controller", code: "BRC1E63", kind: "material", qty: 1, costCents: 10101, source: "assumed" },
  { system: "Upstairs", group: "Pipe, power and controls", name: "Wi-Fi interface", code: "BRP15B61", kind: "material", qty: 1, costCents: 17061, source: "said", why: "“WIFI DONGLES FOR BOTH”" },
  { system: "Shared", group: "Shared", name: "Shale Grey trunking, 2.4 m lengths", code: "TCAPSG", kind: "material", qty: 8, costCents: 3030, source: "said", why: "one run for both, from you" },
  { system: "", group: "Labour", name: "Install: ducted and a split", kind: "labour", qty: 54, unit: "h", costCents: 11200, source: "assumed", why: "40 h ducted and 14 h split, from your past installs" },
  { system: "", group: "Labour", name: "Duct redesign allowance", kind: "labour", qty: 3, unit: "h", costCents: 11200 },
];

const C75: CaseLine[] = [
  { system: "Split system", group: "Pipe, power and controls", name: "Pair coil 1/4 + 1/2, 20 m roll", code: "PC1412", kind: "material", qty: 1, costCents: 19100 },
  { system: "Split system", group: "Pipe, power and controls", name: "Interconnect 3C+E", kind: "material", qty: 20, unit: "m", costCents: 180 },
  { system: "Split system", group: "Pipe, power and controls", name: "TPS 2.5 mm²", kind: "material", qty: 25, unit: "m", costCents: 198 },
  { system: "Split system", group: "Pipe, power and controls", name: "RCBO 20 A", kind: "material", qty: 1, costCents: 3886 },
  { system: "Split system", group: "Pipe, power and controls", name: "Isolator 20 A", code: "ALSIPW201", kind: "material", qty: 1, costCents: 2279 },
  { system: "Split system", group: "Pipe, power and controls", name: "Rubber feet", code: "CMADJ", kind: "material", qty: 1, costCents: 1372 },
  { system: "Split system", group: "Pipe, power and controls", name: "Drain hose", kind: "material", qty: 1, unit: "m", costCents: 305 },
  { system: "", group: "Labour", name: "Install: 4 people, a full day", kind: "labour", qty: 32, unit: "h", costCents: 11200, source: "said", why: "“yes it’s a hard job”" },
];

export const BRIEF_CASES: BenchCase[] = [
  {
    job: "3377",
    title: "Two ducted systems, underfloor downstairs and roof space upstairs (Mitsubishi)",
    brief:
      "Lead from Mitsubishi Electric Australia: 2 storey, 6 bed, 2 bath, potential underfloor duct or multi heads. Luke: two ducted; downstairs underfloor 10-12 kW, six 350 x 150 floor grilles; core holes to rear kitchen; 200 mm core hole through thick sandstone to rear living; upstairs 3 bedrooms, round ceiling grilles; outdoors western side; single phase. Floor plan: downstairs 84 m², upstairs 44 m².",
    settings: DA_OCT_2026,
    options: [{ name: "Two ducted systems", lines: C77, quotedExGstCents: 2281599 }],
    knownGap: "The sandstone core and the kitchen core holes are not priced (no core-drilling allowance set); labour is 40 h a system from past installs, not from the notes.",
    outcome: "Built by hand 6 Oct 2026; to be confirmed by Isaac",
  },
  {
    job: "3384",
    title: "Ducted upstairs and a 7.1 kW split downstairs (Daikin), zoning and a bigger split as options",
    brief:
      "Luke: \"Downstairs 7kw High Wall Split / Ducted upstairs\", \"WIFI DONGLES FOR BOTH\". Plan: upstairs Master 4.0x5.2, Bed 2 2.9x4.2, Bed 3 4.6x3.2, Bed 4 3.6x3.2; downstairs open plan 82 m². Switchboard single phase 63 A with a solar/battery changeover. Isaac: Daikin all units, upstairs 8.5 kW, 20 m pipe runs both, one shared Shale Grey run (8 lengths), zoning as an option with a hallway spill.",
    settings: DA_OCT_2026,
    options: [
      { name: "Ducted upstairs, Cora 7.1 kW downstairs", lines: O1, quotedExGstCents: 1644874 },
      { name: "With a zone for each bedroom", lines: O2, quotedExGstCents: 1727851 },
      { name: "With a 9.5 kW unit downstairs", lines: O3, quotedExGstCents: 1779987 },
    ],
    knownGap: "No Daikin data pack: pipe sizes and circuits assumed. Option 3 came from a compare, not the hand build.",
    outcome: "Built by hand 6 Oct 2026; to be confirmed by Isaac",
  },
  {
    job: "3375",
    title: "Client-supplied 6 kW Mitsubishi split, outdoor on the parapet",
    brief: "Client supplies MSZ-AP60VGD2 and MUZ-AP60VG2. Outdoor on the parapet wall. Four people, a full day: \"yes it's a hard job\".",
    settings: DA_OCT_2026,
    options: [{ name: "Install the client's split", lines: C75, quotedExGstCents: 497689 }],
    outcome: "Approved, sent and ACCEPTED by the client, 6 Oct 2026",
  },
];
