/* A-16, the supabase-js half: the queue's merge gate with BOOKING subjects,
   through real PostgREST (two-way phase 3, PR B).

     set -a; . <the scratch project's env file>; set +a
     node scripts/sm8-bookings-merge-gate.mts

   WHAT IT PROVES. enqueueSm8Writes (src/lib/integrations/sm8-writes.ts)
   puts a fresh row in with
     .upsert(rows, { onConflict: "org_id,dedupe_key", ignoreDuplicates: true })
   and the queue helpers read rows back with .in("dedupe_key", keys). The
   key is GENERATED by the database (kind:job:subject, sm8_writes_safety.sql),
   and a booking's subjects carry colons and a "T" — a slot, a status change,
   an Undo, a Clear — and a slot given back gains ":was:<id>". So, through
   supabase-js and PostgREST for real, with every key built by the app's own
   dedupeKey and bookingSubject (never a string written here):
   1. the first upsert of each booking row comes back with its id, under the
      key the app builds;
   2. the same upsert again comes back empty, and leaves exactly one row;
   3. .in("dedupe_key", keys) finds every one of them;
   4. a slot given back (queueBookIn's release: its subject gains
      ":was:<id>") is found under its new key and not its old one, and the
      old key takes a fresh row.
   The rows it made are deleted at the end. Each run uses a job and people
   of its own, so it never meets another run's rows.

   WHERE IT MAY RUN: only a scratch project whose sm8_writes has row level
   security off, with that project's PUBLISHABLE key. Never a service key,
   and NEVER PRODUCTION: a URL naming production's project ref is refused
   before anything is sent. SUPABASE_URL, SUPABASE_KEY and A16_ORG_ID come
   from the environment alone, never from an .env file.

   Not part of the app, and jest never runs it (it lives outside src/). One
   line per case, PASS or FAIL; the exit code is non-zero on any FAIL. */

import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import * as nodeModule from "node:module";
import { createClient } from "@supabase/supabase-js";

/** Production's project ref: any URL that names it is refused. */
const PRODUCTION_REF = "gilnylvxymxkiucwajgz";

function refuse(why: string): never {
  console.error(`REFUSED: ${why}`);
  process.exit(2);
}

const url = process.env.SUPABASE_URL ?? "";
const key = process.env.SUPABASE_KEY ?? "";
const orgId = process.env.A16_ORG_ID ?? "";
if (!url || !key || !orgId) refuse("SUPABASE_URL, SUPABASE_KEY and A16_ORG_ID must all be set in the environment");
if (url.includes(PRODUCTION_REF)) refuse("that is production's project; this runs only against a scratch project");
if (/^sb_secret_/.test(key)) refuse("a secret key; this runs with the scratch project's publishable key only");
{
  /* an old-style key is a JWT naming its role */
  const [, body] = key.split(".");
  try {
    if (body && JSON.parse(Buffer.from(body, "base64url").toString("utf8")).role === "service_role") {
      refuse("a service_role key; this runs with the scratch project's publishable key only");
    }
  } catch {
    /* not a JWT: a publishable key */
  }
}

/* The app's own modules import each other without a file extension (the
   bundler resolves them); plain node needs one, so a relative import from a
   .ts file that names none is tried as .ts. Only for this process. */
const hooks = nodeModule as unknown as {
  registerHooks?: (h: {
    resolve: (specifier: string, context: { parentURL?: string }, next: (s: string, c: unknown) => unknown) => unknown;
  }) => void;
};
if (!hooks.registerHooks) refuse("this needs node 22.15 or later (module.registerHooks)");
hooks.registerHooks({
  resolve(specifier, context, next) {
    if (specifier.startsWith(".") && context.parentURL?.endsWith(".ts") && !/\.[cm]?[jt]s$/.test(specifier)) {
      const candidate = new URL(`${specifier}.ts`, context.parentURL);
      if (existsSync(fileURLToPath(candidate))) return next(candidate.href, context);
    }
    return next(specifier, context);
  },
});

const { dedupeKey } = await import("../src/lib/integrations/sm8-write-plan.ts");
const { bookingSubject } = await import("../src/lib/integrations/sm8-booking-plan.ts");

const db = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
const TABLE = "sm8_writes";

let failed = 0;
function report(ok: boolean, name: string, detail = ""): void {
  if (!ok) failed += 1;
  console.log(`${ok ? "PASS" : "FAIL"}  ${name}${detail ? ` — ${detail}` : ""}`);
}

/* a job and two people of this run's own */
const job = randomUUID();
const isaac = randomUUID();
const verb = randomUUID();
const tenant = "a16-scratch";
const day = "2026-10-06";

type Made = { id: string; dedupe_key: string };
const upsert = async (row: Record<string, unknown>) =>
  db.from(TABLE).upsert([row], { onConflict: "org_id,dedupe_key", ignoreDuplicates: true }).select("id, dedupe_key");

const common = (subject: string) => ({
  org_id: orgId,
  tenant_id: tenant,
  kind: "booking",
  sm8_job_uuid: job,
  subject,
  payload: { name: "A16" },
  remote_uuid: randomUUID(),
  /* never queued: nothing here is ever for a sender */
  status: "cancelled",
  last_error: "A-16 merge gate (scratch)",
  verb_id: verb,
});

const madeKeys: string[] = [];

async function gate(name: string, row: Record<string, unknown>, subject: string): Promise<string | null> {
  const want = dedupeKey("booking", job, subject);
  madeKeys.push(want);
  const first = await upsert(row);
  const got = (first.data ?? []) as Made[];
  report(
    !first.error && got.length === 1 && !!got[0].id && got[0].dedupe_key === want,
    `${name}: the first upsert comes back with its id, under the app's key`,
    first.error
      ? `${first.error.code} ${first.error.message}`
      : got.length === 1 && got[0].dedupe_key === null
        ? "its dedupe_key came back NULL: this database doesn't GENERATE the key (sm8_writes_safety.sql:113-114), so no upsert can ever meet a clash"
        : `key ${got[0]?.dedupe_key ?? "(none)"}`
  );
  const second = await upsert({ ...row, remote_uuid: randomUUID() });
  const again = (second.data ?? []) as Made[];
  const { count } = await db.from(TABLE).select("id", { count: "exact", head: true }).eq("org_id", orgId).eq("dedupe_key", want);
  report(
    !second.error && again.length === 0 && count === 1,
    `${name}: the same upsert again comes back empty and leaves one row`,
    second.error ? `${second.error.code} ${second.error.message}` : `came back ${again.length}, rows ${count}`
  );
  return got[0]?.id ?? null;
}

const slotSubject = bookingSubject.slot(isaac, `${day} 20:00:00`);
const statusSubject = bookingSubject.status("2026-09-27 16:00:00");
const slotRow = () => ({
  ...common(slotSubject),
  op: "create",
  booking_staff_uuid: isaac,
  booking_start: `${day} 20:00:00`,
  booking_end: `${day} 21:00:00`,
  booking_zone: "Australia/Sydney",
});

async function cases(): Promise<void> {
  /* 1 and 2, for each of a booking row's four shapes */
  const createId = await gate("a booking (slot)", slotRow(), slotSubject);
  await gate(
    "a status change",
    {
      ...common(statusSubject),
      op: "update",
      target_uuid: job,
      job_status_from: "Quote",
      job_status_to: "Work Order",
      seen_edit_date: "2026-09-27 16:00:00",
    },
    statusSubject
  );
  if (createId) {
    const undoSubject = bookingSubject.undo(createId);
    await gate("an Undo", { ...common(undoSubject), op: "delete", depends_on: createId }, undoSubject);
  }
  const activity = randomUUID();
  const clearSubject = bookingSubject.clear(activity);
  await gate(
    "a Clear",
    {
      ...common(clearSubject),
      op: "delete",
      target_uuid: activity,
      booking_staff_uuid: isaac,
      booking_start: `${day} 09:00:00`,
      booking_end: `${day} 11:00:00`,
    },
    clearSubject
  );

  /* 3. .in finds them all, by the app's keys */
  {
    const { data, error } = await db.from(TABLE).select("dedupe_key").eq("org_id", orgId).in("dedupe_key", madeKeys);
    const found = new Set(((data ?? []) as { dedupe_key: string }[]).map((r) => r.dedupe_key));
    report(
      !error && madeKeys.every((k) => found.has(k)) && found.size === madeKeys.length,
      `.in("dedupe_key", …) finds all ${madeKeys.length} booking keys`,
      error ? `${error.code} ${error.message}` : `found ${found.size}`
    );
  }

  /* 4. a slot given back moves its key, and frees the old one */
  if (!createId) return;
  const released = `${slotSubject}:was:${createId}`;
  const { data, error } = await db
    .from(TABLE)
    .update({ subject: released })
    .eq("org_id", orgId)
    .eq("id", createId)
    .eq("status", "cancelled")
    .eq("subject", slotSubject)
    .select("id, dedupe_key");
  const moved = (data ?? []) as Made[];
  const newKey = dedupeKey("booking", job, released);
  report(
    !error && moved.length === 1 && moved[0].dedupe_key === newKey,
    "a slot given back (:was:<id>) moves its generated key",
    error ? `${error.code} ${error.message}` : `key ${moved[0]?.dedupe_key ?? "(none)"}`
  );
  const oldKey = dedupeKey("booking", job, slotSubject);
  const byNew = await db.from(TABLE).select("id").eq("org_id", orgId).in("dedupe_key", [newKey]);
  const byOld = await db.from(TABLE).select("id").eq("org_id", orgId).in("dedupe_key", [oldKey]);
  report(
    !byNew.error && !byOld.error && (byNew.data ?? []).length === 1 && (byOld.data ?? []).length === 0,
    ".in finds the given-back row under its new key, and nothing under the old one",
    `new ${(byNew.data ?? []).length}, old ${(byOld.data ?? []).length}`
  );
  const fresh = await upsert(slotRow());
  const freshRows = (fresh.data ?? []) as Made[];
  report(
    !fresh.error && freshRows.length === 1 && freshRows[0].id !== createId && freshRows[0].dedupe_key === oldKey,
    "the old key takes a fresh row",
    fresh.error ? `${fresh.error.code} ${fresh.error.message}` : `came back ${freshRows.length}`
  );
}

try {
  await cases();
} finally {
  /* the rows this run made go, whatever happened above: its own job's only */
  const { error } = await db.from(TABLE).delete().eq("org_id", orgId).eq("sm8_job_uuid", job);
  if (error) console.error(`(couldn't delete this run's rows under job ${job}: ${error.code} ${error.message})`);
}

console.log(failed === 0 ? "ALL PASS" : `${failed} FAILED`);
process.exit(failed === 0 ? 0 : 1);
