// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/action-required" | "/dashboard/admin" | "/dashboard/admin/holidays" | "/dashboard/admin/organization" | "/dashboard/admin/rate-calculator" | "/dashboard/assets" | "/dashboard/my-leave" | "/dashboard/my-timesheet" | "/dashboard/my-vehicle" | "/dashboard/notices" | "/dashboard/profile" | "/dashboard/studio" | "/dashboard/studio/data-library" | "/dashboard/team" | "/dashboard/team/[staff]" | "/dashboard/tiff" | "/dashboard/tiff/knowledge" | "/dashboard/timepay" | "/dashboard/timepay/leave" | "/dashboard/toolbox" | "/dashboard/toolbox/heat-load" | "/dashboard/toolbox/outdoor-unit" | "/dashboard/toolbox/running-pressures" | "/dashboard/toolbox/troubleshooting" | "/hq" | "/hq/changes" | "/hq/data" | "/hq/data/[brand]" | "/hq/map" | "/hq/orgs/[id]" | "/invite/error" | "/live/[token]"
type AppRouteHandlerRoutes = "/invite/accept"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard" | "/hq"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/dashboard": {}
  "/dashboard/action-required": {}
  "/dashboard/admin": {}
  "/dashboard/admin/holidays": {}
  "/dashboard/admin/organization": {}
  "/dashboard/admin/rate-calculator": {}
  "/dashboard/assets": {}
  "/dashboard/my-leave": {}
  "/dashboard/my-timesheet": {}
  "/dashboard/my-vehicle": {}
  "/dashboard/notices": {}
  "/dashboard/profile": {}
  "/dashboard/studio": {}
  "/dashboard/studio/data-library": {}
  "/dashboard/team": {}
  "/dashboard/team/[staff]": { "staff": string; }
  "/dashboard/tiff": {}
  "/dashboard/tiff/knowledge": {}
  "/dashboard/timepay": {}
  "/dashboard/timepay/leave": {}
  "/dashboard/toolbox": {}
  "/dashboard/toolbox/heat-load": {}
  "/dashboard/toolbox/outdoor-unit": {}
  "/dashboard/toolbox/running-pressures": {}
  "/dashboard/toolbox/troubleshooting": {}
  "/hq": {}
  "/hq/changes": {}
  "/hq/data": {}
  "/hq/data/[brand]": { "brand": string; }
  "/hq/map": {}
  "/hq/orgs/[id]": { "id": string; }
  "/invite/accept": {}
  "/invite/error": {}
  "/live/[token]": { "token": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
  "/hq": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
