// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/dashboard/action-required/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/action-required">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/action-required/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/holidays/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/holidays">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/holidays/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/organization">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/rate-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/rate-calculator">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/rate-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/assets">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/my-leave/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/my-leave">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/my-leave/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/my-timesheet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/my-timesheet">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/my-timesheet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/my-vehicle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/my-vehicle">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/my-vehicle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/notices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notices">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/notices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/studio/data-library/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/studio/data-library">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/studio/data-library/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/studio">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/team/[staff]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/team/[staff]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/team/[staff]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/team/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/team">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/team/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/tiff/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tiff/knowledge">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/tiff/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/tiff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tiff">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/tiff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/timepay/leave/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timepay/leave">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/timepay/leave/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/timepay/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/timepay">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/timepay/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/toolbox/heat-load/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/toolbox/heat-load">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/toolbox/heat-load/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/toolbox/outdoor-unit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/toolbox/outdoor-unit">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/toolbox/outdoor-unit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/toolbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/toolbox">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/toolbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/toolbox/running-pressures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/toolbox/running-pressures">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/toolbox/running-pressures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/toolbox/troubleshooting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/toolbox/troubleshooting">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/toolbox/troubleshooting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hq/changes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hq/changes">> = Specific
  const handler = {} as typeof import("../../src/app/hq/changes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hq/data/[brand]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hq/data/[brand]">> = Specific
  const handler = {} as typeof import("../../src/app/hq/data/[brand]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hq/data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hq/data">> = Specific
  const handler = {} as typeof import("../../src/app/hq/data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hq/map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hq/map">> = Specific
  const handler = {} as typeof import("../../src/app/hq/map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hq/orgs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hq/orgs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/hq/orgs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hq">> = Specific
  const handler = {} as typeof import("../../src/app/hq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invite/error">> = Specific
  const handler = {} as typeof import("../../src/app/invite/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/live/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live/[token]">> = Specific
  const handler = {} as typeof import("../../src/app/live/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/invite/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/invite/accept">> = Specific
  const handler = {} as typeof import("../../src/app/invite/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/hq/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/hq">> = Specific
  const handler = {} as typeof import("../../src/app/hq/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
