/* The sieve's vocabulary in the other languages spoken on site.

   `sniff.ts` holds the English lists and the scoring; this holds the same
   four categories in Mandarin, Vietnamese, Arabic, Spanish and Tagalog. Two
   files rather than one because the two halves are read for different
   reasons: the scoring is a decision to defend, and this is a word list to
   extend — and extending it is meant to feel cheap.

   IT IS SAFE TO BE GENEROUS HERE, and that is the sieve's own asymmetry
   rather than a shortcut. A wrong yes costs one routing call whose proposal
   comes back empty and is silently dropped. A wrong no means a tradesperson
   dictated a job for somebody and was never offered it — invisible to them
   and to us. Every word below only ever turns a no into a yes, so a loose
   entry costs pennies and a missing one costs the feature.

   ONE RULE WORTH KEEPING. These lists are read against ALL languages at
   once, so a word that means something ordinary in another language will
   fire there too. That is tolerable in exactly this file (a wasted call)
   and NOT tolerable in `lib/brain/intent.ts` (an eaten note) — do not copy
   entries between the two on the assumption that a cue is a cue.

   Arabic and Chinese match as substrings — Arabic prefixes its conjunctions
   and articles onto the word, Chinese has no spaces at all — so their
   entries are stems rather than whole words on purpose. */

/** Words that put a job on somebody. */
export const OBLIGATION_CUES: readonly string[] = [
  // Spanish
  "hay que",
  "tiene que",
  "tienes que",
  "tenemos que",
  "hace falta",
  "necesita",
  "necesitamos",
  "necesito",
  "debe",
  "debemos",
  "no olvides",
  "no olvidar",
  "acuérdate",
  "acuerdate",
  "avisa a",
  "avísale",
  "dile a",
  "pregúntale",
  "pregunta a",
  "por favor",
  // Vietnamese
  "cần",
  "phải",
  "nhớ",
  "đừng quên",
  "nhắc",
  "nói với",
  "bảo",
  "nhờ",
  "yêu cầu",
  // Tagalog — "paki" is the request prefix and matches pakibili, pakicheck…
  "kailangan",
  "dapat",
  "paki",
  "wag kalimutan",
  "huwag kalimutan",
  "sabihin kay",
  "tanungin",
  "ipaalam",
  // Arabic
  "يجب",
  "لازم",
  "محتاج",
  "نحتاج",
  "تحتاج",
  "لا تنسى",
  "تذكر",
  "اسأل",
  "بلغ",
  // Chinese
  "需要",
  "必须",
  "别忘",
  "记得",
  "提醒",
  "告诉",
  "麻烦",
];

/** Things you do to a job rather than record about it. */
export const IMPERATIVE_CUES: readonly string[] = [
  // Spanish — both the imperative and the infinitive, because a dictated
  // list says "pedir rejillas" as often as "pide las rejillas"
  "pide",
  "pedir",
  "cambia",
  "cambiar",
  "revisa",
  "revisar",
  "llama",
  "llamar",
  "manda",
  "mandar",
  "envía",
  "enviar",
  "trae",
  "traer",
  "arregla",
  "arreglar",
  "instala",
  "instalar",
  "quita",
  "quitar",
  "cotiza",
  "cotizar",
  "factura",
  "facturar",
  "agenda",
  "agendar",
  "recoge",
  "recoger",
  "reemplaza",
  "reemplazar",
  // Vietnamese
  "đặt",
  "thay",
  "gọi",
  "gửi",
  "mang",
  "sửa",
  "kiểm tra",
  "lấy",
  "đổi",
  "lắp",
  "tháo",
  "báo giá",
  "hẹn",
  // Tagalog
  "bumili",
  "bilhin",
  "palitan",
  "tawagan",
  "ipadala",
  "dalhin",
  "ayusin",
  "tingnan",
  "kunin",
  "tanggalin",
  "iskedyul",
  // Arabic
  "اطلب",
  "استبدل",
  "غير",
  "اتصل",
  "ارسل",
  "احضر",
  "اصلح",
  "افحص",
  "ركب",
  "فك",
  // Chinese
  "订购",
  "更换",
  "打电话",
  "检查",
  "安装",
  "拆",
  "报价",
  "预约",
  "安排",
];

/** When. A deadline is the strongest single signal that a sentence is about
    something that has to happen, rather than something that is true. */
export const DEADLINE_CUES: readonly string[] = [
  // Spanish
  "hoy",
  "esta noche",
  "mañana",
  "lunes",
  "martes",
  "miércoles",
  "miercoles",
  "jueves",
  "viernes",
  "sábado",
  "sabado",
  "domingo",
  "próxima semana",
  "proxima semana",
  "esta semana",
  "próxima visita",
  "proxima visita",
  "antes de",
  "cuanto antes",
  "urgente",
  // Vietnamese
  "hôm nay",
  "tối nay",
  "ngày mai",
  "thứ hai",
  "thứ ba",
  "thứ tư",
  "thứ năm",
  "thứ sáu",
  "thứ bảy",
  "chủ nhật",
  "tuần sau",
  "tuần này",
  "lần sau",
  "gấp",
  "khẩn",
  // Tagalog
  "ngayon",
  "mamaya",
  "bukas",
  "martes",
  "miyerkules",
  "huwebes",
  "biyernes",
  "sabado",
  "linggo",
  "susunod na linggo",
  "ngayong linggo",
  "susunod na bisita",
  "madali",
  // Arabic
  "اليوم",
  "الليلة",
  "غدا",
  "بكرة",
  "الاثنين",
  "الثلاثاء",
  "الاربعاء",
  "الأربعاء",
  "الخميس",
  "الجمعة",
  "السبت",
  "الاحد",
  "الأحد",
  "الاسبوع القادم",
  "الأسبوع القادم",
  "عاجل",
  // Chinese
  "今天",
  "今晚",
  "明天",
  "后天",
  "星期",
  "周一",
  "周二",
  "周三",
  "周四",
  "周五",
  "周六",
  "周日",
  "下周",
  "这周",
  "下次",
  "紧急",
  "尽快",
];

/** Something is wrong, which is how a flag sounds. */
export const FAULT_CUES: readonly string[] = [
  // Spanish
  "no funciona",
  "no enfría",
  "no enfria",
  "roto",
  "rota",
  "avería",
  "averia",
  "averiado",
  "fuga",
  "gotea",
  "falla",
  "fallo",
  "saltó",
  "salto el",
  "atascado",
  "obstruido",
  "alarma",
  "otra vez",
  "sigue sin",
  // Vietnamese
  "không hoạt động",
  "hỏng",
  "rò rỉ",
  "chảy nước",
  "lỗi",
  "kẹt",
  "tắc",
  "quá nhiệt",
  "báo lỗi",
  "vẫn chưa",
  // Tagalog
  "hindi gumagana",
  "sira",
  "tumutulo",
  "butas",
  "may problema",
  "barado",
  "nag-trip",
  "ulit",
  "hindi pa",
  // Arabic
  "لا يعمل",
  "ما يشتغل",
  "معطل",
  "مكسور",
  "تسريب",
  "يسرب",
  "عطل",
  "مسدود",
  "انذار",
  "مرة اخرى",
  "ما زال",
  // Chinese
  "不工作",
  "坏了",
  "漏水",
  "故障",
  "报警",
  "堵",
  "卡住",
  "过热",
  "跳闸",
  "还没",
];
